# Exported from Render on 2024-05-19T14:38:42Z
databases:
- name: webui-database
  databaseName: webui_database
  user: webui_database_user
  plan: starter
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
- name: webui-database-dev
  databaseName: webui_database
  user: webui_database_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: superprompt-webui
  runtime: python
  repo: https://github.com/calebcauthon/superprompt-webui
  plan: starter
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
- type: web
  name: superprompt-webui-dev
  runtime: python
  repo: https://github.com/calebcauthon/superprompt-webui
  plan: starter
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  branch: dev
version: "1"
